version: '2'
services:
    redis:
        image: registry.lil.tools/library/redis:6.0.11
    web:
        build: .
        image: docker.pkg.github.com/jcushman/actions-test/web:latest
        volumes:
            - .:/app
        depends_on:
            - redis
        tty: true
