version: '2.2'
services:
    redis:
        image: redis:6.0.11
    web:
        image: jcushman/actions-test:0.2-57080bb91f666032c00ab95a8fb323e8
        volumes:
            - .:/app
        depends_on:
            - redis
        tty: true
