version: '2.2'
services:
    redis:
        image: registry.lil.tools/library/redis:6.0.11
    web:
        build:
            context: .
            cache_from:
                - ghcr.io/jcushman/actions-test/web:0.1
        image: ghcr.io/jcushman/actions-test/web:0.1
        volumes:
            - .:/app
        depends_on:
            - redis
        tty: true
