name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      ### build docker image ###

      - name: Get current image and tag name
        id: update-image
        uses: harvard-lil/docker-compose-update-action@main
        with:
          rebuild-if-changed: "Dockerfile"
          image: "jcushman/actions-test"
          git-email: "lil@law.harvard.edu"
          registry-user: ${{ secrets.REPOSITORY_USER }}
          registry-pass: ${{ secrets.REPOSITORY_TOKEN }}

      - name: Build docker image locally for pull request
        if: github.event_name == 'pull_request' && steps.update-image.outputs.updated == '1'
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ steps.update-image.outputs.image-tag }}

      ### start docker-compose ###

      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml up -d
      - name: Show running containers
        run: docker ps -a
      - name: Show logs
        run: docker-compose logs

      ### run tests ###

      - name: Run test suite
        shell: 'script -q -e -c "bash {0}"'
        run: docker-compose exec web ls /app